format = '$status$battery$directory$kubernetes $git_branch$git_state$git_status($git_metrics)$character '


[directory]
truncate_to_repo = false

[status]
symbol = '🔴 ERROR: $status '
success_symbol = '🟢 '
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]] 
threshold = 30
style = 'bold yellow'
[[battery.display]]
threshold = 100
style = 'bold green'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false
ignore_submodules = false
include_staged = true

[git_status]
format = ' -> $ahead_behind$staged$deleted$untracked'
staged = '[🚀 $count](green) | '
deleted = '[🗑 $count](red) | '
untracked = '[🤷 $count](blue) | '
ahead = '[⇡$count](green) | '
behind = '[⇣$count](red) | '

[golang]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\([$context:$namespace]($style)\)'
disabled = false

[os]
format = '\[[$symbol]($style)\]'
